version: '3'

volumes:
  db-data:
    external: false

services:
  db:
    env_file: .env
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"

  app:
    env_file: .env
    build: .
    volumes:
      - "$PWD:/home/app/webapp"
    ports:
      - "3000:3000"
    depends_on:
      - db

  jobs:
    env_file: .env
    build: .
    volumes:
      - "$PWD:/home/app/webapp"
    command: bundle exec rake jobs:work
    depends_on:
      - db