version: '3'

volumes:
  db-data:
    external: false

  odsa-books:
    external: false

services:
  db:
    env_file: .env
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"

  app:
    env_file: .env
    build: .
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - "odsa-books:/home/app/webapp/public/OpenDSA/Books"
    depends_on:
      - db

  jobs:
    env_file: .env
    build: .
    volumes:
      - "odsa-books:/home/app/webapp/public/OpenDSA/Books"
    command: bundle exec rake jobs:work
    depends_on:
      - db