  legacy:
    adapter: mysql2
    host: localhost
    database: opendsa_lti
    port: 3306
    username: opendsa
    password: opendsa

  old_db:
    adapter: mysql2
    host: localhost
    database: opendsa_lti
    port: 3306
    username: opendsa
    password: opendsa