# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5578c763371b8da40c427457113c0428ddf9f8311acf12c60723b38778a8ca926ad417cf0d0dbfb8f09fc369f1dddb48a6f062327e12f0bbe1cf5a6279903039

test:
  secret_key_base: b337485cfab23eb51242cec5de86a1d780a77c4f36be23ab9ad950e1265cf4a9d6206509e6aee3faec388447559e571e21da31247af741e0396fcedc427760c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
